lst = [1, 2, 3, 4 ,5]
print(type(lst))
print(len(lst))
lst.append(6)
print(lst)
lst.insert(0,0)
print(lst)
lst.extend([7, 8, 9])
print(lst)
lst.remove(7)
print(lst)
lst.sort()
print(lst)
lst.sort(reverse=True)
print(lst)
print(max(lst))
print(min(lst))

line = list("Rameshvarman")
print(line)